# -*- coding: utf-8 -*-
"""Tarea 1 - Segunda clase - IA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kP9kKQWHMFj3G84I25iRIFYSZbuweV0r
"""

import pandas as pd
import matplotlib.pyplot as plt
iris = "/content/iris.csv"

class Resumen:
  def __init__(self):
        self.data_frame = pd.read_csv(iris).drop('variety',axis=1)

  def Est_resumen(self):
      self.Resumen = self.data_frame.describe()
      print(self.Resumen)

  def Variables(self):
      self.Vars = self.data_frame.columns.values
      print(self.Vars)

  def Ests(self,var):
      self.var = var
      self.Media = round(self.data_frame[self.var].mean(),2)
      self.Mediana = round(self.data_frame[self.var].median(),2)
      self.Desviación = round(self.data_frame[self.var].std(),2)
      self.Q1 = round(self.data_frame[self.var].quantile(0.25),2)
      self.Q2 = round(self.data_frame[self.var].quantile(0.5),2)
      self.Q3 = round(self.data_frame[self.var].quantile(0.75),2)
      self.Hist = plt.hist(self.data_frame[self.var], bins=5, color='blue', edgecolor='black')
      plt.xlabel(self.var)
      plt.ylabel('Frecuencia')
      plt.title('Histograma')
      print("Variable=",self.var,"Media=",self.Media,"Mediana=",self.Mediana, "Desviación=",self.Desviación,
            "Q1=",self.Q1,"Q2=",self.Q2,"Q3=",self.Q3)
      plt.show()

pet = Resumen()
pet.Est_resumen()
pet.Variables()
pet.Ests('petal.length')