# -*- coding: utf-8 -*-
"""Tarea 1 - Primera clase - IA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BNkI5wQs0eoYVNOK-08t4Tv2At-xJ0fT
"""

import pandas as pd
import matplotlib.pyplot as plt
iris = "/content/iris.csv"

class ITER:
    def __init__(self, valor):
        self.data_frame = pd.read_csv(iris)
        self.limite = self.data_frame.shape[0]
        self.dato = self.data_frame.iloc[valor]
        self.valor = valor

    def __iter__(self):
        return self

    def __next__(self):
        if self.valor < self.limite-2:
            resultado = self.data_frame.iloc[self.valor+1],self.data_frame.iloc[self.valor+2]
            self.valor += 1
            return resultado
        else:
            print("Error")
            raise StopIteration

# Crear una instancia
flor = ITER(0)

# Usar un bucle
for elemento in flor:
    print(elemento)